name: DoGame

on:
  issues:
    types: [opened]

jobs:
  transformImage:
    name: Run Game
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'Update:')

    permissions:
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          architecture: "x64"

      - name: Running Game
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          pip install -r requirements.txt
          python main.py

      - name: Commit and push changes
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${ISSUE_TITLE} by ${ISSUE_AUTHOR}"
          git push
